### ISSUE TITLE
HS Student Resource Portal

### ISSUE THREAD

**Issue by dwai213** [pioneers/website#111]
Future works:
A place (portal) that links to student resources (badge requests, forum, wiki, emails to contact, kit extension requests)
Can also double as infrequent season announcement page

**Comment by viviehn** [comment]
@dwai213 @chuen0630 Bringing this back up - do we still want this to happen? Or does Discourse cover this? I like the idea, but if our goal is to centralize resources, maybe it's better just putting it all on Discourse.

**Comment by dwai213** [comment]
You make a good point.
But the way discourse is run is that it’s spun up anew every single year (because there’s no good, easy way to hide/delete old posts)
So every year we would need to duplicate work, like adding event information, links to resources, etc.
But that’s not necessarily terrible because resources might get out of date

From the student perspective, it's also helpful for them to Google "Pioneers in Engineering", hit our main website, and then have a bunch of links that would take them to Discourse, Kit Extension Purchasing, Purchase records, event information instead of remembering discourse.p.o , extension.p.o, history.p.o ... etc

I’ll leave it up to @chuen0630 and Clancy Lee to decide, but I think either path sounds good to me

**Comment by viviehn** [comment]
Update: So I think our final conclusion is what Dennis suggested - a page with links to various resources (Discourse, Kit Ext, etc.)

Would be nice if this were something more than just a list of links, but even that at the very least would be helpful.

**Comment by dwai213** [comment]
Cool @j-m-h and @baby-bell, just wanted to keep you guys in the loop about how you should disseminate your app to the students.
There will be a page somewhere on p.b.e/student-stuff that has a link to everything the students need
