### ISSUE TITLE
README.md needs to reflect Docker building instructions 

### ISSUE THREAD

**Issue by dwai213** [pioneers/website#124]
Either have the commands written in the README.md file or have a bash script also included to expedite the build procedure (preferred). Have these instructions be included and labeled as a dokku-less running instructions. (This will probably be dev instructions)

@cwang395 can you update the readme with running instructions in the case that dokku is installed?

**Comment by scottnuma** [comment]
@dwai213 Should the build have a specific tag? I've been using pie-jekyll for my test builds and numascott/jekyll else.

**Comment by dwai213** [comment]
I think pie-jekyll is good. But pie-website is just as good and tells the function as well.

Although it turns out that because we are using [dokku](https://github.com/dokku/dokku) to deploy the website, dokku actually renames the image and container that website is run.

(Screenshot of containers running on DigitalOcean right now. website.web.1 is our jekyll instance)[https://www.dropbox.com/s/1s1hytgq6flkdhp/Screenshot%202016-02-14%2010.44.07.png?dl=0]

**Comment by scottnuma** [comment]
Dockumentation is now up on the wiki [here](https://github.com/pioneers/website/wiki/Docker). Some definition or phrasing about what Docker is may need editing.

**Comment by dwai213** [comment]
I see you Mr. Dockumentation

**Comment by dwai213** [comment]
I changed up your bash script so that the container is run after image is built
#173

**Comment by dwai213** [comment]
Since we are putting a bunch of this stuff on Github wiki, we should have a note/reference in the actual README.md of this repo to tell readers to go there instead of detailed Dockumentation (which is great btw)
