### ISSUE TITLE
Remove double link to same asset

### ISSUE THREAD

**Issue by dwai213** [pioneers/website#134]
[on this page](http://pierobotics.org/support-pie/donate.html) and [on this page](http://pierobotics.org/support-pie/sponsors.html), you link to the 2015-2016 sponsorship packet.

It might be easy to forget update links to something so specific in two (at least) different places on the website, especially in a year from now.
I would recommend having one of the two link be a redirect link to the other page to make maintenance for this asset easier.

**Comment by quantumfusion** [comment]
Another option would be to establish a file like a settings file that would contain the actual path to the pdf. Then both of these pages could reference this settings file to discover the path. This maintains the current ease of discovery for the user and simplifies maintenance.
