### ISSUE TITLE
Annual report links still point to pioneers.berkeley.edu

### ISSUE THREAD

**Issue by cwang395** [pioneers/website#138]
@quantumfusion where should we host these? Is storing them as static assets an option?

**Comment by dwai213** [comment]
@quantumfusion , weren't you thinking of s3 or a gcloud bucket?

**Comment by quantumfusion** [comment]
@ryanjulian already has a Google Cloud account that we're using for the various binaries the kit needs. I think its the best place to put them, albeit a bit annoying to maintain. Otherwise, I'm ok with hosting as static assets for the time being.

**Comment by dwai213** [comment]
static asset means including it as part of the repo?

**Comment by quantumfusion** [comment]
As a temp measure, yes. That is fine. We can look into doing cdn stuff
properly later in the season.
