### ISSUE TITLE
Many hrefs loaded from http sources

### ISSUE THREAD

**Issue by ryanjulian** [pioneers/website#147]
This makes browsers show our https page as insecure, among other things. Also, pioneers.allen.li can go down at any time.

**Comment by cwang395** [comment]
Hi Ryan,

Can you tell us the specific file and line where we reference pioneers.allen.li? I did a search in the directory, but the only reference I can find is in commented out code.

**Comment by ryanjulian** [comment]
I found one yesterday, but can't find it again today. Perhaps it was eliminated in a resent push?

Anyway, the actual issue (not as severe as the original title) is that many href's are going to http endpoints (rather than https). This makes the browser not display the page as secure, since it has http content.

**Comment by jiangdaniel** [comment]
Resolved by #170
