### ISSUE TITLE
Swap out usernames for actual names on blog

### ISSUE THREAD

**Issue by quantumfusion** [pioneers/website#149]
Blog entries are not longer tied to user accounts, so it doesn't make sense to have usernames there.

**Comment by scottnuma** [comment]
Do we know who the user jesca is?

**Comment by quantumfusion** [comment]
jesca is Jessica Wong.

--
Matthew Chang
Advisor, Pioneers in Engineering
Electrical Engineering and Computer Science | 2013
(805) 931-6224 | mattchang@pioneers.berkeley.edu
pioneers.berkeley.edu

**Comment by scottnuma** [comment]
Thanks
