### ISSUE TITLE
Inline hyperlinks difficult to see

### ISSUE THREAD

**Issue by robertluan** [pioneers/website#161]
The colors chosen for text make inline hyperlinks difficult to see (on some displays, at least). 
![image](https://cloud.githubusercontent.com/assets/17400323/13280965/dcc12e7c-da95-11e5-8681-79e8ff8c6747.png)

**Comment by jiangdaniel** [comment]
Do you remember which page these links were on?  I can't seem to find it

**Comment by dwai213** [comment]
this was on the Foundation page

---
Dennis Wai
Advisor, Pioneers in Engineering
(510) 755-9858
denniswai@pioneers.berkeley.edu <mailto:denniswai@pioneers.berkeley.edu>
pioneers.berkeley.edu <http://pioneers.berkeley.edu/>
