### ISSUE TITLE
Historical blog post addresses broken

### ISSUE THREAD

**Issue by robertluan** [pioneers/website#166]
Not a huge deal, but the web addresses of past blog posts are no longer accessible.
e.g. https://pioneers.berkeley.edu/blog/2015/02/27/high-school-seniors-pie-alumni-scholarship-announced-second-year/

**Comment by dwai213** [comment]
Does this mean we will add all old posts back to the website?

**Comment by scottnuma** [comment]
Added all the old posts back into the blog

**Comment by cwang395** [comment]
Fixed by #240
