### ISSUE TITLE
documentation for dokku deployment

### ISSUE THREAD

**Issue by dwai213** [pioneers/website#174]
We should include this information in the wiki as well

**Comment by jiangdaniel** [comment]
I somewhat started the wiki page.  I need help filling in the rest though.  I don't remember what comes before or after the command to push to the server.
https://github.com/pioneers/website/wiki/Deploying-the-website

**Comment by jiangdaniel** [comment]
@dwai213 Do you think that the info in https://github.com/pioneers/website/wiki/Deploying-the-website is sufficient?

**Comment by dwai213** [comment]
lgtm
well done
