### ISSUE TITLE
Add Terry Johnson as a faculty advisor

### ISSUE THREAD

**Issue by jiangdaniel** [pioneers/website#189]
It seems that he has been removed from the page for some reason

**Comment by cwang395** [comment]
D: Is there a specific picture of him that we want on the page? If not I'm going to pick one that I like from googling him. Like [this one](https://media.licdn.com/mpr/mpr/shrinknp_200_200/p/3/000/12a/204/17194a7.jpg), which is used on the BioE website.

**Comment by jiangdaniel** [comment]
There is a picture of him on his website: http://www.terrydjohnson.com

I'm sure that any picture would be fine though
