### ISSUE TITLE
Links to pioneers.berkeley.edu/home are broken

### ISSUE THREAD

**Issue by cwang395** [pioneers/website#203]
[This plugin](https://help.github.com/articles/redirects-on-github-pages/) looks like a promising solution but it seems broken ._.

**Comment by jiangdaniel** [comment]
We could always go the hacky way and create a home.html file and put in the line <meta http-equiv="refresh" content="0; URL='https://pioneers.berkeley.edu'" />

How did the url pioneers.berkeley.edu/home get out anyways?

**Comment by jiangdaniel** [comment]
Or we could try adding some Javascript to the 404 page that says something like
`if (window.location.href == "/home" || window.location.href == "/home/") { window.location.href = origin; }`

That might also work for the scholarship redirect (issue #171)

**Comment by cwang395** [comment]
^ I like this solution
