### ISSUE TITLE
Homepage cover photo is outdated

### ISSUE THREAD

**Issue by scottnuma** [pioneers/website#207]
Realized it might be good to update the homepage with a pic of the latest field.

I dug up some photos out of the drive to get a conversation going on which would be best - if anybody sees other good ones plz comment in.

Option I:
![battle](https://cloud.githubusercontent.com/assets/6622133/16173642/0925be5c-355d-11e6-95e7-2cf8eab65fbe.JPG)

Option II:
![bot](https://cloud.githubusercontent.com/assets/6622133/16173643/09260362-355d-11e6-95e4-d198077a04c3.JPG)

Option III:
![pit](https://cloud.githubusercontent.com/assets/6622133/16173644/092aa9b2-355d-11e6-9524-2f19720cc0d5.JPG)

Option IV:
![soccer](https://cloud.githubusercontent.com/assets/6622133/16173646/09308d5a-355d-11e6-962f-c27a5effba66.JPG)

Option V:
![team](https://cloud.githubusercontent.com/assets/6622133/16173645/092d5fcc-355d-11e6-98d2-b4052efc7ace.JPG)

Option VI:
![working](https://cloud.githubusercontent.com/assets/6622133/16173647/093529e6-355d-11e6-93b8-a64db983b20f.JPG)

**Comment by jiangdaniel** [comment]
In context:

Option I
![screen shot 2016-06-18 at 5 09 31 pm](https://cloud.githubusercontent.com/assets/15041963/16173696/b97f4902-3577-11e6-8d9a-a4e752512244.png)

Option II
![screen shot 2016-06-18 at 5 10 09 pm](https://cloud.githubusercontent.com/assets/15041963/16173698/b98c5782-3577-11e6-98a0-cbc8b0728188.png)

Option III
![screen shot 2016-06-18 at 5 10 27 pm](https://cloud.githubusercontent.com/assets/15041963/16173700/b98c6038-3577-11e6-921d-a799dceb8dcc.png)

Option IV
![screen shot 2016-06-18 at 5 10 48 pm](https://cloud.githubusercontent.com/assets/15041963/16173701/b98f8e02-3577-11e6-8c86-984657ae5537.png)

Option V
![screen shot 2016-06-18 at 5 11 13 pm](https://cloud.githubusercontent.com/assets/15041963/16173697/b98b1b4c-3577-11e6-910b-763ed0805b31.png)

Option VI
![screen shot 2016-06-18 at 5 11 30 pm](https://cloud.githubusercontent.com/assets/15041963/16173706/ea428ff4-3577-11e6-8751-e36b653620be.png)

**Comment by jiangdaniel** [comment]
I think Option I or Option II would be good. I'm leaning toward Option II.

**Comment by scottnuma** [comment]
Ooh thanks - we'll also be able to translate the photos vertically to choose which section of each photo is displayed.

Looking at them in context, I'm feeling more Option II.

**Comment by dwai213** [comment]
How difficult would it be to cycle through a subset of the five you picked?
(They all look great :D)

---
Dennis Wai
Advisor, Pioneers in Engineering
(510) 755-9858
denniswai@pioneers.berkeley.edu <mailto:denniswai@pioneers.berkeley.edu>
pioneers.berkeley.edu <http://pioneers.berkeley.edu/>

**Comment by scottnuma** [comment]
Yus I think I could Porque no Los Dos it with some javascript.

Also @viviehn plz bring the more pics

**Comment by jiangdaniel** [comment]
Resolved by pull request #214
