### ISSUE TITLE
Add final comp video somewhere

### ISSUE THREAD

**Issue by jiangdaniel** [pioneers/website#208]
It's been suggested that we should add the video from Berkeley News to the website somewhere.

http://news.berkeley.edu/2016/04/26/pie-bring-robotics-to-budding-young-engineers/

**Comment by dwai213** [comment]
why not a blog post?

---
Dennis Wai
Advisor, Pioneers in Engineering
(510) 755-9858
denniswai@pioneers.berkeley.edu <mailto:denniswai@pioneers.berkeley.edu>
pioneers.berkeley.edu <http://pioneers.berkeley.edu/>

**Comment by jiangdaniel** [comment]
I think that it should be more visible on the website, because the video explains what PiE does and what PiE is about.  The video is probably better than anything else on the website at giving people an idea of what we do.  It explains our goals, it explains the competition, it shows the biggest event from our competitions (finalcomp), it shows the perspective of a PiE staff, it shows the perspective of a mentor, and it shows the perspective of some high school students.  My only reservations are that the video is fairly long and that it doesn't seem to do that great of a job of showing a diversity in race.

I am under the assumption that most people who are trying to learn about PiE wouldn't go to read the blog.

<img width="905" alt="screen shot 2016-06-19 at 7 47 35 am" src="https://cloud.githubusercontent.com/assets/15041963/16177114/1fd9a40c-35f2-11e6-81b1-16b22b0d6418.png">

From the analytics, it seems that most go to the homepage, rc_spring page, and about_us page.

What do you think?

**Comment by dwai213** [comment]
I think you make a good point, grounded with data. :D

**Comment by jiangdaniel** [comment]
Resolved by commit 1403435
