### ISSUE TITLE
Add page for initiating new members

### ISSUE THREAD

**Issue by scottnuma** [pioneers/website#216]
We are adding new members and it would be convenient to have a landing page for them where they're able to find all the forms they need to sign - rather than email it out to them.

**Comment by scottnuma** [comment]
>So the process involves filling out this online form:
https://docs.google.com/a/pioneers.berkeley.edu/forms/d/1HwOxHDJqh6RpRI5pa3a8u9fyV4J1GpmNAe7XqZdNMUg/viewform

>And the three documents attached. Physically signing them is preferred, but I think electronically filling them out is fine as well

[2017 Individual Contributor License Agreement.pdf](https://github.com/pioneers/website/files/355777/2017.Individual.Contributor.License.Agreement.pdf)
[2017 Staff Emergency Contact Form.pdf](https://github.com/pioneers/website/files/355778/2017.Staff.Emergency.Contact.Form.pdf)
[2017 Staff Liability Form.pdf](https://github.com/pioneers/website/files/355779/2017.Staff.Liability.Form.pdf)

**Comment by viviehn** [comment]
Overheard you talking with @medecinqui about this, what was the verdict? Do we still want this to be available online since setting up the accounts themselves is still a manual process?

**Comment by scottnuma** [comment]
Decided to still make this a page for easy access to the files, but keep it unlisted - so we'd just be sending the url out

**Comment by dwai213** [comment]
just to ask a clarification question, when you talk about digitally signing them, you mean expecting people (new staff) to have some software on their computer to sign it right?

---
Dennis Wai
Advisor, Pioneers in Engineering
(510) 755-9858
denniswai@pioneers.berkeley.edu <mailto:denniswai@pioneers.berkeley.edu>
pioneers.berkeley.edu <http://pioneers.berkeley.edu/>

**Comment by scottnuma** [comment]
Oh I was thinking just having them print it out (should we not have it
printed for them) and then turn it in to somebody who will do the
processing. Alternatively, just a convenient page for staff to grab it from
without digging through the drive.


On July 10, 2016 at 6:14:44 PM, Dennis Wai (notifications@github.com) wrote:

just to ask a clarification question, when you talk about digitally signing
them, you mean expecting people (new staff) to have some software on their
computer to sign it right?

---
Dennis Wai
Advisor, Pioneers in Engineering
(510) 755-9858
denniswai@pioneers.berkeley.edu <mailto:denniswai@pioneers.berkeley.edu>
pioneers.berkeley.edu <http://pioneers.berkeley.edu/>






> On Jul 10, 2016, at 12:30 PM, Scott Numamoto <notifications@github.com>
wrote:
>
> Decided to still make this a page for easy access to the files, but keep
it unlisted - so we'd just be sending the url out
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub <
https://github.com/pioneers/website/issues/216#issuecomment-231606363>, or
mute the thread <
https://github.com/notifications/unsubscribe/AE0RvQvoH-0y5RLBnLqib7-hZo-HhiiJks5qUUhogaJpZM4JItxT
>.
>

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/pioneers/website/issues/216#issuecomment-231622968>,
or mute
the thread
<https://github.com/notifications/unsubscribe/AGULtXskVkoGEaGVIcaF9jBXvvY_jLWYks5qUZkEgaJpZM4JItxT>
.

**Comment by dwai213** [comment]
ah i see. having them print it out is fine

---
Dennis Wai
Mechanical Systems Control Laboratory <http://msc.berkeley.edu/>
University of California at Berkeley
me.berkeley.edu/~dwai <http://me.berkeley.edu/~dwai>
(510) 306-1628 <tel:%28510%29%20306-1628>

**Comment by jiangdaniel** [comment]
I think that Dennis was referring to "And the three documents attached. Physically signing them is preferred, but I think _electronically filling them out is fine as well_"

Could we accept digitally signed forms?  Every Mac comes with Preview, so everyone who has access to a machine running macOS could definitely sign them digitally.

**Comment by scottnuma** [comment]
Oh - that part. In that case, this needs to be part of a larger
conversation about our e-signing methods for school reg and such.

Accepting digitally signed forms seems to me like it would streamline our
process.


On July 11, 2016 at 6:08:02 AM, Daniel Jiang (notifications@github.com)
wrote:

I think that Dennis was referring to "And the three documents attached.
Physically signing them is preferred, but I think *electronically filling
them out is fine as well*"

Could we accept digitally signed forms? Every Mac comes with Preview, so
everyone who has access to a machine running macOS could definitely sign
them digitally.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/pioneers/website/issues/216#issuecomment-231728753>,
or mute
the thread
<https://github.com/notifications/unsubscribe/AGULtfENrh5RCDt997dCjr9DPAoHXo-_ks5qUkAggaJpZM4JItxT>
.

**Comment by dwai213** [comment]
Yep, Daniel’s pretty close.

I think you should keep on doing what you’re doing - having a static page with a PDF copy of all the forms we need.
Once the e-signing method gets implemented, we’ll update this static page.

Thanks!

---
Dennis Wai
Mechanical Systems Control Laboratory <http://msc.berkeley.edu/>
University of California at Berkeley
me.berkeley.edu/~dwai <http://me.berkeley.edu/~dwai>
(510) 306-1628 <tel:%28510%29%20306-1628>

**Comment by jiangdaniel** [comment]
New staff form page was added by @scottnuma with pull request #219.
Thanks Scott
