### ISSUE TITLE
Homepage banner occasionally shows old photo

### ISSUE THREAD

**Issue by jiangdaniel** [pioneers/website#217]
Vivien and Christian reported that they would occasionally see a flash of the old banner right before a new one loads in.

**Comment by jiangdaniel** [comment]
@scottnuma Do you have any ideas on how to prevent the old image from showing up?  I'm thinking of maybe removing the reference to the old image entirely

**Comment by scottnuma** [comment]
Yeah, removing the banner is possible - it would just show up as blank
while the other image loads, which would be more professional. Indicating a
blank background in html would break the banner for the small fraction of
our users who disabled javascript (e.g. Nikita's phone). I think the
audience is small enough to be fine. I also need to optimize the file sizes
for faster loading times.

**Comment by jiangdaniel** [comment]
Resolved by pull request #220
