### ISSUE TITLE
Link colors are inconsistent

### ISSUE THREAD

**Issue by cwang395** [pioneers/website#230]
Sometimes they're blue, sometimes they're gold. Not sure why.

**Comment by jiangdaniel** [comment]
Are we sure that we want to make the links gold in the first place?  At least with the current shade of gold, they don't offer very good contrast, which seems like an accessibility problem

**Comment by jiangdaniel** [comment]
<img width="614" alt="screen shot 2016-08-10 at 9 03 35 pm" src="https://cloud.githubusercontent.com/assets/15041963/17576173/f427d9e4-5f3d-11e6-9ad0-b2398eb26a7b.png">

**Comment by jiangdaniel** [comment]
The blue on the other hand:
<img width="557" alt="screen shot 2016-08-10 at 9 05 43 pm" src="https://cloud.githubusercontent.com/assets/15041963/17576204/4185abd0-5f3e-11e6-843f-d7d2d1c19ba2.png">

**Comment by viviehn** [comment]
I guess the arguments for the gold are that it stands out against regular text better, and provides more visual interest - we do use a lot of blue on the site and barely any gold. Though I will be the first to admit in terms of color preference I'd choose the blue over the gold every time.

So yeah, idk

**Comment by dwai213** [comment]
I am a bigger fan of the blue links ;)

**Comment by jiangdaniel** [comment]
We should probably decide on something for this.  The inconsistent link colors is pretty weird.  Sounds like blue is generally preferred?  Should we revert back to all blue? @viviehn

**Comment by jiangdaniel** [comment]
Addressed by PR #265
