### ISSUE TITLE
Old blog post images

### ISSUE THREAD

**Issue by jiangdaniel** [pioneers/website#244]
Some old blog posts are missing images.  Basically, any old blog post image with a relative url is missing because the image has not been added to the repo.

**Comment by viviehn** [comment]
Most blog posts do not have images and would probably look better with them, but I don't know how reasonable it is to dig up pictures for them. Also, this? http://pioneers.berkeley.edu/blog/2013/03/16/Cube-Route/ Not sure if that picture is intentional, lol.

**Comment by jiangdaniel** [comment]
We can do our best to grab images for old blog posts if someone requests them.  Otherwise, it probably isn't worth the effort
