### ISSUE TITLE
Make infographic clickable

### ISSUE THREAD

**Issue by quantumfusion** [pioneers/website#251]
https://pierobotics.org/get-involved/join-staff.html
Helpful to be able to click on infographic to facilitate pinch to zoom

**Comment by jiangdaniel** [comment]
I added a link for the infographic to open a new tab in https://github.com/jiangdaniel/website/commit/5ae55b26d22f5d1e7710371d27da4134b3a7c193.  However, I will wait for my PR #260 to get merged before sending a new PR with the changes that address this issue (I forgot to create a feature branch before making changes, so I want to avoid any weirdness with sending another PR)

**Comment by jiangdaniel** [comment]
Addressed by PR #261
