### ISSUE TITLE
Update Board of Directors

### ISSUE THREAD

**Issue by scottnuma** [pioneers/website#258]
1. Board of Directors on the foundation page

https://pioneers.berkeley.edu/about/foundation.html

The officers of the board are now:
Tomoya Ogura (CEO)
Winston Long (Secretary)
Douglas Hutchings (Treasurer)
I don't think the title is relevant on the website, so alphabetical by name is fine.

The new board of directors:

Winston Long
Douglas Hutchings
are no longer on the board

Daniel Lee
Dennis Wai
are now in their stead.

[Relevant  Email](https://share.polymail.io/v1/z/s/u_qwXPhZgEQXGzEv/OXTwiJvvSKNFidri34BXYsOzZrEH2AXy2I4duYhylaSb2tUffFtu9d66qGuImy9Jdw_Ct5M7HRuRD_Hl9i2BwpWcsNFSjnXMGs0=)

**Comment by dwai213** [comment]
+1

**Comment by jiangdaniel** [comment]
Addressed by PR #257
