### ISSUE TITLE
Statistics on our about page

### ISSUE THREAD

**Issue by scottnuma** [pioneers/website#259]
Statistics on our about page - https://pioneers.berkeley.edu/about/about-us.html
The 350 student figure for 2015 suggests we had a large improvement in the number of students than the years prior, which is false.

The choice of what figure we use is kinda difficult: it's important to consider the difference between # of students signed up, # of students attending kickoff (a lot, probably), and # of students attending final comp (a bit less, and possibly a more accurate number of students impacted?). There's a conflict between accuracy and impressiveness.

I think @Winston might be a good resource on the actual numbers here. I know I don't really know.

Another minor thing is that the conversion from chronological year to year-in-PiE's-Operation is pretty bad. I guess it's just me, but I have a hard time going 2015 = Year 7. Perhaps something to denote 2015 is the 7th year of PiE's operation might be interesting information?

Also, updating the figure for 2016 (Year 8) would be good.

Lastly, there was a discussion about how putting #students, #mentors, and #schools on the same axes doesn't quite work: if anything, comparing people to schools sounds weird. Perhaps comparing students and mentors on one graph, and attaching number of schools in a different way would be good?
Would comparing the student vs mentors value be interesting?
This is a much more multifaceted problem that I'm sure you can figure out better on your own time.

[Relevant Email](https://share.polymail.io/v1/z/s/u_qwXPhZgEQXGzEv/OXTwiJvvSKNFidri34BXYsOzZrEH2AXy2I4duYhylaSb2tUffFtu9d66qGuImy9Jdw_Ct5M7HRuRD_Hl9i2BwpWcsNFSjnXMGs0=)

**Comment by jiangdaniel** [comment]
Conversation continued on #280
