### ISSUE TITLE
Refactor "Programs" navbar item

### ISSUE THREAD

**Issue by cwang395** [pioneers/website#277]
It's getting a little long. I want to move the fall/spring robotics competition pages into their own navbar menu (something like "Competitions"), and rename "Programs" to "Other Programs".

**Comment by jiangdaniel** [comment]
Somewhat related, is the [Open Source](http://pioneers.github.io/opensource/index.html) link still relevant?

**Comment by jiangdaniel** [comment]
Also, is there a point in keeping the "Past Programs" page?

**Comment by viviehn** [comment]
These sound like questions for @medecinqui

**Comment by medecinqui** [comment]
@cwang395 I mean, sure we can see how refactoring all of that will look. I think that's a cool idea.
@jiangdaniel That's a question on whether we're keeping programs we've historically had on the website or not. Do we think people will be interested in seeing what happened to PREP? We can refer people to that page on the website when we talk about what programs we used to have - I was thinking that would be useful in case there were interested schools. As for PREP open source, that's essentially part of PREP.

**Comment by cwang395** [comment]
Let's refactor the navbar to the following:

1. About
    - About Us
    - The PiE Team
    - Foundation
    - Gallery
1. **Compete**
    - Fall Competition
    - Spring Competition
    - Start a Team
    - Past Participants
1. Programs
    - Fall Workshops
    - Open Source
    - Scholarship
    - Past Programs
1. Get Involved
    - Join PiE Staff
    - Become a Mentor
    - Volunteer
    - FAQ
1. Support PiE
    - How You Can Help
    - List of Sponsors
1. Blog

Reasoning:

* The robotics competition(s) are our main offering, and having information about them all in one place makes more sense than scattering it across multiple navbar tabs. Pulling "Start a Team" out of "Get Involved" also makes the purpose of this tab more targeted towards people who want to *contribute*, rather than participate in the competition.
* Past Participants should be moved out into its own page to keep info pages more focused and make it easier for people who actually just want to see past participants to find what they want.
    * This also helps with #112

**Comment by dwai213** [comment]
👍

**Comment by jiangdaniel** [comment]
Addressed by #290
