### ISSUE TITLE
Move "past participants" off the spring competition page?

### ISSUE THREAD

**Issue by cwang395** [pioneers/website#278]

**Comment by dwai213** [comment]
Maybe, you can move the past participants information under "Get Involved" --> "Schools/Start a Team"?

**Comment by viviehn** [comment]
@dwai213 WE ARE ON THE SAME WAVELENGTH. That was my exact idea - only realization was that schools might prefer to be listed under the Spring Comp page for more visibility? Not sure if that's something anyone cares about though

**Comment by dwai213** [comment]
IMO, I think if a school’s name is on our website, it’s good enough for people to “verify” that they were a part of PiE competition. I would think it’s ok

**Comment by jiangdaniel** [comment]
Addressed by #290
