### ISSUE TITLE
Add a timeline of major competition events to the spring competition page

### ISSUE THREAD

**Issue by cwang395** [pioneers/website#279]
Create an interactive timeline of the major events in the spring (main) competition:
1.  Kickoff
2. Game day
3. Scrimmage
4. Final comp

Each major event in the timeline can be expanded to show a brief description. I'd like to use this to replace the 6 not-very-informative icons and captions we have on the page. The rest of the page will remain unchanged.

[Fall Comp timeline sketch.pdf](https://github.com/pioneers/website/files/546036/Fall.Comp.timeline.sketch.pdf)

**Comment by viviehn** [comment]
http://line25.com/tutorials/how-to-create-flat-style-breadcrumb-links-with-css

**Comment by cwang395** [comment]
11/16 update:

Done:

* Started adding JavaScript to make the timeline expand/collapse properly for both small and large screens

To do:

* Actually make the code work 😛 
* Change the colors
* Timeline labels are a bit off center

**Comment by cwang395** [comment]
11/30 update:

Done:
* Finished JS to make descriptions on large screens toggle

To do:
* Small screen panel descriptions are broken :/
