### ISSUE TITLE
update get-involve/forms

### ISSUE THREAD

**Issue by chuen0630** [pioneers/website#316]
Can someone update /get-involve/forms? I want to replace the link to the google form with Cognito Form (https://www.cognitoforms.com/PioneersInEngineering/NewStaffRegistration) and also remove emergency contacts attachment as it is already on the Cognito Form. 

Additionally, we can consider embedding the Cognito Form to the page using either HTML given by the CognitoForm UI here :

<div class="cognito">
<script src="https://services.cognitoforms.com/s/2JccztZj5ECcSf6u5HN1zg"></script>
<script>Cognito.load("forms", { id: "1" });</script>
</div>

or

<iframe src="https://services.cognitoforms.com/f/2JccztZj5ECcSf6u5HN1zg?id=1" style="position:relative;width:1px;min-width:100%;*width:100%;" frameborder="0" scrolling="yes" seamless="seamless" height="666" width="100%"></iframe>
<script src="https://services.cognitoforms.com/scripts/embed.js"></script>

**Comment by chuen0630** [comment]
I would like to have a slight change to this page. People are getting confused and printed out everything, including the google form (but gosh they never hit the submit button). I would like to dicomission the google form and have nothing but the CognitoForm on the page. If the new staff doesn't feel comfortable with digital signature, they will get links to the pdf in the cognito form. So there's no need to have it on this page.

**Comment by viviehn** [comment]
#342
