### ISSUE TITLE
Design Review Time

### ISSUE THREAD

**Issue by scottnuma** [pioneers/website#320]
[The time stated for design reviews is 4PM](https://pioneers.berkeley.edu/compete/rc-spring.html). They actually take place during a range of times, depending on what the team schedules. This statement might be misleading for those planning ahead.

**Comment by viviehn** [comment]
will switch to TBD, thanks Scott!

**Comment by viviehn** [comment]
https://github.com/pioneers/website/pull/321

**Comment by jiangdaniel** [comment]
Resolved
