### ISSUE TITLE
White lines on the chevron

### ISSUE THREAD

**Issue by scottnuma** [pioneers/website#341]
On the [RC Competition page](https://pioneers.berkeley.edu/compete/rc-spring.html), white lines are still popping up for me.

![screen shot 2017-03-15 at 11 01 55 pm](https://cloud.githubusercontent.com/assets/6622133/23983854/986ee1e2-09d3-11e7-8d76-a85b2cb2c1e6.png)

**Comment by scottnuma** [comment]
jk it works while I'm running Docker on Vivien's master branch - looks like it's already fixed.

**Comment by viviehn** [comment]
The issue occurs when viewing at not 100% screen, not sure how to fix. :(
