### ISSUE TITLE
update website for 2017-2018 season

### ISSUE THREAD

**Issue by kev-chien** [pioneers/website#357]
Just starting this issue so to make a list of things that could be updated (copying over items from previous issue #224  which has some separate topics):

Website-wide
- [ ] Add new dates to the robotics competition schedules
- [ ] About Us
- [ ] Add new photos:
   - [ ] Homepage pictures (2017 game)
   - [ ] Gallery, update with photos from 2016-2017
   - [ ] Join PiE Staff: new Staff Photo
   - [ ] FAQ slides
   - [ ] Basically every single webpage hero image

About Us
- [ ]  Update Fall section in About Us (currently is about PiE Prep)
- [ ]  Add 2016 - 2017 Annual Report, and 2015 - 2016
- [ ]  Add 2016 - 2017 data to chart, and 2015 - 2016
- [ ]  Make chart static image - to be cuter and fit Andy's "aesthetic" better
- [ ] The PiE Team <-- all members with photos and desc

People/ Projects
- [ ] New PMs and images
- [ ] New projects/ description
- [ ] Add some people to alumni section?
- [ ]  Do the above with jekyll datafiles
- [ ] Foundation

Does the list of Foundation members need to change at all?

Robotics Competition
- [ ] Add schools to list of past participants #347 
- [ ] Switch video to 2016 Berkeley News interview?
- [ ] Update schedule
- [ ] Become a mentor
- [ ] Banner saying comp is outdated

- [ ] Update description

Sponsors
- [ ] Update list of sponsors?
- [ ] Why Support PiE section at beginning

**Comment by viviehn** [comment]
Random thought:
https://pioneers.berkeley.edu/support-pie/donate.html
It'd be nice if this page had a "Why Support PiE" section at the beginning

**Comment by charleshong3** [comment]
This is applicable every year, now for 2020-2021

**Comment by charleshong3** [comment]
Nvm, made new issue #575. Closing
