### ISSUE TITLE
Decal --> DeCal 

### ISSUE THREAD

**Issue by dwai213** [pioneers/website#370]
https://github.com/pioneers/website/blob/ae0276f7df3e63a9bd3528fabc313c1a3fcea45a/_includes/header.html#L56

**Comment by kev-chien** [comment]
Right lol

**Comment by dwai213** [comment]
+1 yeee

**Comment by kev-chien** [comment]
Closed by #374

**Comment by dwai213** [comment]
Cool thanks!
