### ISSUE TITLE
Website nav bar doesn't collapse into hamburger fast enough?

### ISSUE THREAD

**Issue by viviehn** [pioneers/website#391]
@ArjunSridhar1 pointed out that the breakpoint to switching to the hamburger nav bar view could be more aggressive (there's a point where it doesn't switch to hamburger, and just makes the different nav tabs on a separate line, which obscures part of the page)

**Comment by kev-chien** [comment]
Thanks @viviehn, this is mentioned in #369 as well but we'll get to it!
