### ISSUE TITLE
[Operation Site Revamp] About Us Page

### ISSUE THREAD

**Issue by kev-chien** [pioneers/website#394]
Notes:
- We want to consolidate About Us into 1 page, with the following sections: (using the style of homepage sections)

**Our Story**
- [ ] Basically, a short blurb of the history of PiE (founding) and its mission.
- [ ] Some picture or visual component: Maybe a timeline, or photo of PiE Year One.

**meet the team**
- [ ] implement section with meet the team, including leadership
- [ ] horizontal scroll component with PM's depending on screen size (see `_styles.scss` for horizontal scroll)
- [ ] link to an actual page containing all the team members (to be updated in #373)

**Gallery**
- [ ] horizontal scroll component with images conveying the idea of competition, and activities staff are involved in
- [ ] link to an actual page of comprehensive Gallery

**Facts and Statistics Page**
- [ ] move charts into a separate statistics page
- [ ] have a link to the facts and statistics page
- [ ] move/ include 1 or 2 statistics into the homepage
  - [ ] the (almost half of students' families make less than US median wage)
  - [ ] could compare to students' incomes in other robotics competitions (i.e. FIRST)
- Annual Data:
  - [ ] change annual data into a line graph
  - [ ] take out the part about schools

**Foundation**
- [ ] Keep but maybe update style.

**Annual Reports**
- [ ] Annual Reports --> Make an _include element and include the annual reports on this page and on the Sponsors Page. And instead of a table, add "document" graphics, or make them block/ card elements (date added is not needed).

**Things to move/ copy to other pages**
- [ ] Add Foundation details perhaps to Support Us (or a Heading + link in Support Us to "learn more about Pioneers Foundation, our nonprofit org which manages donations"
- [ ] Move RC Comp details to home page (admittedly it's currently very nice... but I think we can move on)

**Comment by dwai213** [comment]
@kev-chien and @viviehn , would it possible to keep the Foundation place where it is?
Foundation is the legal, nonprofit entity for PiE so it does make sense for it to be in the About Us section. 
Although PiE 501(c)3 Foundation's tax information does make sense in the Support Us section, the other information largely isn't.

**Comment by dwai213** [comment]
As for `link to an actual page containing all the team members`, see #89 
Maybe there can be some overlap to address #89 in what you are doing here :D

**Comment by kev-chien** [comment]
Agreed on Foundation, updated the issue.
Also, I'm not sure what #89 is suggesting explicitly, or what's the best way to implement. Does it mean to upload all PiE Staff's resumes onto the website, with emails/info to verify/ for companies to contact, or some way for staff to check the website to see if resumes are updated?

**Comment by scottnuma** [comment]
Perhaps Ryan can help shed some light on the intention here

Scott Numamoto

**Comment by dwai213** [comment]
I believe one idea is to, at the minimum, just have a running list of all past members. (maybe only include at least 1-2 years of active membership?) so that if someone were to check if Kev Chien was ever PM of weebdev, then his name will appear in a Google search of “Kev Chien weebdev PiE”

Dennis Wai
dwai213@gmail.com

**Comment by kev-chien** [comment]
For the most part done. Can look back for ideas on what else to implement.
