### ISSUE TITLE
Include Laser Cut Files for PiE on the Road

### ISSUE THREAD

**Issue by scottnuma** [pioneers/website#403]
Hi web team,

Can you include our laser cutter files on the PiE on the Road web page? Perhaps as an FAQ of "Can I get a copy of your laser cutter templates?" but I defer to what you feel works best for the page.

You can find the files in [this Google Drive folder](https://drive.google.com/drive/u/3/folders/0B1ItMveYgOqEbUZMdEgzSlJNaUk).

**Comment by kev-chien** [comment]
Done!
