### ISSUE TITLE
101 O'Brien Directions

### ISSUE THREAD

**Issue by scottnuma** [pioneers/website#448]
Did we still have the page that had the directions for how to get to 101 O'Brien? Can I get the link to it for directing mentors?

If not, can we restore it - possibly as a unlinked URL accessible page if it doesn't fit within the structure well?

**Comment by kev-chien** [comment]
It is in the FAQ portion of get-involved in [https://pioneers.berkeley.edu/get-involved/#faq](https://pioneers.berkeley.edu/get-involved/#faq), in the drop-down for "when/where does PiE meet?". But I can try to make it more visible or somewhere in the site-map, or on the mentors page.

**Comment by kev-chien** [comment]
Possible solutions:
I think we could make references to 101 O'Brien be a clickable link to the google map (or perhaps a new web page). Also, we could have a description of PiE's address in the footer of every page, where there is contact information, and a link to the map.

**Comment by scottnuma** [comment]
Yeah, I think something more visible / explicit would be good. The only use case I'm looking for is a URL to direct mentors to for instructions.

**Comment by kev-chien** [comment]
A map link is now at the [become mentor](https://pioneers.berkeley.edu/get-involved/become-mentor) page and the [join staff](https://pioneers.berkeley.edu/get-involved/) page and at the sitemap footer in the [map] link, so closing issue for now. In the future could also bit.ly the google maps... and maybe transfer ownership to a pie account lol
