### ISSUE TITLE
Photo carousel buttons in dialog also rotate through non-selected group

### ISSUE THREAD

**Issue by quantumfusion** [pioneers/website#476]
Link: https://pierobotics.org/about/

To Reproduce:
1. Click on Kevin Ma
1. Click on left arrow in dialog
1. Observe Tommy's photo

Expectation:
1. Click on Kevin Ma
1. Click on left arrow in dialog
1. Observe Kevin Chien's photo

**Comment by kev-chien** [comment]
Resolved in #479. We removed clicking and carousel-ing entirely for non-bio staff photos.
Of note is that Bios currently do not have carousel-ing, which could be added in the future.
