### ISSUE TITLE
Use Git LFS for assets

### ISSUE THREAD

**Issue by jonathan-j-lee** [pioneers/website#511]
The Git history and tree is bloated and makes any automation unusable (takes forever to check out):
```
$ du -h -d 1
56K	./_data
24K	./about
324M	./_site
40K	./_includes
57M	./kit
268K	./_posts
4.4M	./.sass-cache
20K	./gallery
64K	./software
16K	./support-pie
16K	./_plugins
20K	./pie-on-the-road
32K	./_script
265M	./assets
40K	./_layouts
28K	./programs
12K	./staffonly
56K	./compete
1.2G	./.git
32K	./get-involved
136K	./_csv_scraper
8.0K	./blog
472K	./_sass
1.9G	.
```

**Comment by scottnuma** [comment]
Appears that Dokku does not support LFS and does not plan to
https://github.com/dokku/dokku/issues/2401
Doesn't appear anyone else has done it either with a little bit of Googling

I don't think this is viable unless we either

- do not host the website on Dokku 
- store images separately and serve from a CDN

**Comment by jonathan-j-lee** [comment]
That's too bad.
