### ISSUE TITLE
Update "Projects" section of "Get Involved" to reflect changes 

### ISSUE THREAD

**Issue by charleshong3** [pioneers/website#542]
https://pioneers.berkeley.edu/get-involved/#projects

- Update PMs of all projects
- GDC and GIC -> Atlas
- Website -> 
- Business -> Corporate and Public Relations

**Comment by smtaha512** [comment]
Can you please describe the issue a bit? I am new to open source so I want to contribute.

**Comment by charleshong3** [comment]
Hi, this isn't really an open source project, it's in a public repository but this is a task to be done within our organization. Sorry for the confusion!

**Comment by chaoryan5** [comment]
https://github.com/pioneers/website/pull/544
