### ISSUE TITLE
Prep Open source

### ISSUE THREAD

**Issue by dHutchings** [pioneers/website#66]
Hey!

I know that the prep open source page is a little outside your domain, but it's really wierd when you go to the prep open source page.  The header bar for prep open source is different, and that's really confusing.

**Comment by cwang395** [comment]
Hi Doug,

The small arrow icon to the right of the Prep Open Source link in the navbar is meant to indicate that it opens in an external page. We decided to include that link because the current website's navbar links there. Do you know the motivation for linking to that page in the current website's navbar?

**Comment by dHutchings** [comment]
If I were to guess, the motivation was

1. We had to have it somewhere publicly accessible from our website
2. It was part of some larger open source effort on our part that folded.

**Comment by cwang395** [comment]
Is open source no longer active? In that case, we can remove that navbar link.

**Comment by dHutchings** [comment]
Uh...

Well I know for sure it's not been edited in years.  But I think it'd be a
disservice to those who made it to wholesale remove it.

Do you know how easy / hard it'd be to bring open source up to current
stylistic guidelines?

-Doug

On Wed, Feb 3, 2016 at 11:16 PM, Christine Wang <notifications@github.com>
wrote:

> Is open source no longer active? In that case, we can remove that navbar
> link.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pioneers/website/issues/66#issuecomment-179685311>.
>



-- 
Douglas Hutchings
Treasurer, Pioneers in Engineering Foundation
(408) 489-1041 | douglashutchings@pioneers.berkeley.edu
http://pioneers.berkeley.edu

**Comment by cwang395** [comment]
Probably not terribly hard, but that's something for later. For now, I think the icon indicating that the link opens to an external website should suffice.
