### ISSUE TITLE
No PiE logo on firefox tab

### ISSUE THREAD

**Issue by dHutchings** [pioneers/website#70]
Hey!

It would be very cool if there was a minature PiE-logo on the firefox tab that opens the website.  Like, you know, what happens for google drive or gmail or almost every other commercial website.

<img width="283" alt="screen shot 2016-02-03 at 11 11 39 pm" src="https://cloud.githubusercontent.com/assets/2158534/12808411/8ca2382a-cacb-11e5-91ba-428998d4ed83.png">

**Comment by tobinsarah** [comment]
If it's helpful, here's what the current website (pierobotics.org) does for tab image:
![screen shot 2016-02-04 at 7 43 48 pm](https://cloud.githubusercontent.com/assets/3431933/12837525/90a47ade-cb78-11e5-974f-4fe4de605f36.png)
