### ISSUE TITLE
Different pictures for PMS

### ISSUE THREAD

**Issue by tobinsarah** [pioneers/website#76]
Grant's image shows two people, which is confusing. Krystyn's image mostly shows orange chairs so you don't really see her.

And of course, you still need photos for a bunch of PMS. Have you tried looking through Tommy [staff roster photos](https://drive.google.com/drive/u/1/folders/0B9nXRdBdUPMYZWx4WF9uQV8zeVU)?

**Comment by cwang395** [comment]
Hi Tobin,

We have looked through the staff roster photos, and these were all the ones we could find for the people who were listed as project managers. If more photos get added, let us know and we'll be happy to include them.

**Comment by jiangdaniel** [comment]
We updated some PM images in PR #257.  When we update the PM list to reflect this year's PMs, we will do our best to find better photos
