### ISSUE TITLE
Mousing over "Events" and "Annual Reports" looks a bit weird to me

### ISSUE THREAD

**Issue by tobinsarah** [pioneers/website#78]
perhaps change the color indicating mouse over? Right now it's close enough to gray in the white/gray list setup that it looks like the list messed up. (Maybe blue or gold for mouse-over? Or maybe it just looks weird to me...)
![screen shot 2016-02-04 at 8 14 17 pm](https://cloud.githubusercontent.com/assets/3431933/12838843/8e21b560-cb87-11e5-9e0c-dbb462674c3a.png)

**Comment by cwang395** [comment]
Hi Tobin,

This is expected behavior. It comes from the Bootstrap templates we used and is a pretty common pattern in other websites.
