### ISSUE TITLE
Title images

### ISSUE THREAD

**Issue by tobinsarah** [pioneers/website#79]
- [x] Some pages don't have an image at all -- just grey rectangle behind the title. (Title page; Support PiE; PiE Sponsors)
- [x] The "PiE Sponsors" page title is white text in front of a (mostly) white banner -- looks weird.
- [x] Why Baymax on the "Start a Team" page? Cute, but seems unrelated...
- [x] "Robotics Competition" and "Join PiE Staff" pages have the same image (I would use [one of these for Staff](https://drive.google.com/drive/u/1/folders/0B3bafdwXkXBgfkx5b2ZDYTdhQ3BodXdESEMtTFBFRjJHVnVhd3dsek9MWmVJd0tCY09VeGs)
- [ ] "The PiE Team" and "Gallery" use the same image.
- [ ] The "PREP" image has been cropped so all you see is people's torsos... better image/positioning please.

**Comment by cwang395** [comment]
Most likely due to incorrect paths or images D:

**Comment by jiangdaniel** [comment]
Separated into distinct issues
