### ISSUE TITLE
Foundation should have a page under About Us

### ISSUE THREAD

**Issue by ryanjulian** [pioneers/website#87]
It should include legal status/financial information, EIN, board of directors, etc.

Feel free to bother the foundation to write this for you.

**Comment by dwai213** [comment]
Besides EIN, a 501(c)(3) tag, what kind of financial information outside of the annual reports were you thinking of @ryanjulian ?

**Comment by dwai213** [comment]
Additional things to consider:
Going Forward, full page with a standard 501(c)(3) disclosure. We can also put Mike Rosen helped us in that new page, email to foundation if they need a gift receipt, Federal Tax ID number, Organization mission statement, organizational contact name, mailing address. This information might be provided to small random donors that slip through the cracks

Overall reduced visibility with Foundation

**Comment by dwai213** [comment]
Addressed by #152

**Comment by dwai213** [comment]
Addressed by #160
